# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 06:45


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('wakawaka', '0001_initial')]

    operations = [
        migrations.RemoveField(model_name='wikipage', name='content_type'),
        migrations.RemoveField(model_name='wikipage', name='object_id'),
    ]
