# Generated by Django 4.2.14 on 2024-07-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakawaka', '0002_auto_20160409_0645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revision',
            options={'get_latest_by': 'modified', 'ordering': ('-modified',), 'verbose_name': 'Revision', 'verbose_name_plural': 'Revisions'},
        ),
        migrations.AlterModelOptions(
            name='wikipage',
            options={'ordering': ('slug',), 'verbose_name': 'Wiki page', 'verbose_name_plural': 'Wiki pages'},
        ),
        migrations.AlterField(
            model_name='revision',
            name='creator_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='creator ip'),
        ),
    ]
